# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        # Cache key includes OS, Python version, and hash of requirements.txt
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
        path: ~/.cache/pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest

    - name: Verify dependencies
      run: |
        pip list

    - name: Run Tests
      run: |
        pytest

    #        pytest tests/test_icons.py
    #        pytest tests/test_main.py

    #    - name: Install pytest-xdist
    #      run: |
    #        pip install pytest-xdist
    #
    #    - name: Run Tests in Parallel
    #      run: |
    #        pytest -n auto tests/